// Code generated by avrogen. DO NOT EDIT.

package primitive

import (
	"github.com/amedia/avro/avrotypegen"
)

type R struct {
	Intfield    int              `json:"intField"`
	Longfield   int64            `json:"longField"`
	Floatfield  float32          `json:"floatField"`
	Doublefield float64          `json:"doubleField"`
	Boolfield   bool             `json:"boolField"`
	Bytesfield  []byte           `json:"bytesField"`
	Stringfield string           `json:"stringField"`
	Nullfield   avrotypegen.Null `json:"nullField"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"intField","type":"int"},{"name":"longField","type":"long"},{"name":"floatField","type":"float"},{"name":"doubleField","type":"double"},{"name":"boolField","type":"boolean"},{"name":"bytesField","type":"bytes"},{"name":"stringField","type":"string"},{"name":"nullField","type":"null"}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
			2: true,
			3: true,
			4: true,
			5: true,
			6: true,
			7: true,
		},
	}
}
